[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]

remmapings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "v2-core/=lib/v2-core/",
    "v2-periphery/=lib/v2-periphery/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
