[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.remappings]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"v2-core/" = "lib/v2-core/"
"v2-periphery/" = "lib/v2-periphery/"
